CREATE SCHEMA "auth";

CREATE SCHEMA "encyclopedia";

CREATE SCHEMA "pet";

CREATE SCHEMA "social";

CREATE SCHEMA "notification";

CREATE TABLE "auth"."users" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "email" varchar UNIQUE NOT NULL,
                                "username" varchar UNIQUE NOT NULL,
                                "password" varchar NOT NULL,
                                "role" varchar,
                                "avatar_url" text,
                                "bio" text,
                                "is_verified" boolean,
                                "created_at" timestamp,
                                "deleted_at" timestamp
);

CREATE TABLE "auth"."follow_user" (
                                      "follower_id" bigint,
                                      "following_id" bigint,
                                      "created_at" timestamp,
                                      PRIMARY KEY ("follower_id", "following_id")
);

CREATE TABLE "encyclopedia"."classes" (
                                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "name" varchar NOT NULL,
                                          "code" varchar UNIQUE,
                                          "description" text
);

CREATE TABLE "encyclopedia"."species" (
                                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "class_id" bigint,
                                          "name" varchar NOT NULL,
                                          "scientific_name" varchar,
                                          "description" text
);

CREATE TABLE "encyclopedia"."species_attributes" (
                                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     "species_id" bigint,
                                                     "key" varchar NOT NULL,
                                                     "value_min" numeric,
                                                     "value_max" numeric,
                                                     "unit" varchar,
                                                     "display_order" int
);

CREATE TABLE "encyclopedia"."species_sections" (
                                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "code" varchar UNIQUE NOT NULL,
                                                   "display_name" varchar NOT NULL,
                                                   "description" text
);

CREATE TABLE "encyclopedia"."species_section_contents" (
                                                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           "species_id" bigint,
                                                           "section_id" bigint,
                                                           "language" varchar,
                                                           "content" text
);

CREATE TABLE "encyclopedia"."breeds" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "species_id" bigint,
                                         "name" varchar NOT NULL,
                                         "origin" varchar,
                                         "short_description" text
);

CREATE TABLE "encyclopedia"."breed_attributes" (
                                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   "breed_id" bigint,
                                                   "key" varchar NOT NULL,
                                                   "value" varchar,
                                                   "display_order" int
);

CREATE TABLE "encyclopedia"."breed_sections" (
                                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "code" varchar UNIQUE NOT NULL,
                                                 "display_name" varchar,
                                                 "description" text
);

CREATE TABLE "encyclopedia"."breed_section_mapping" (
                                                        "breed_id" bigint,
                                                        "section_id" bigint,
                                                        "display_order" int,
                                                        PRIMARY KEY ("breed_id", "section_id")
);

CREATE TABLE "encyclopedia"."breed_section_contents" (
                                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                         "breed_id" bigint,
                                                         "section_id" bigint,
                                                         "language" varchar,
                                                         "content" text
);

CREATE TABLE "encyclopedia"."media" (
                                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "entity_type" varchar,
                                        "entity_id" bigint,
                                        "type" varchar,
                                        "role" varchar,
                                        "url" text,
                                        "display_order" int
);

CREATE TABLE "pet"."pets" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar,
                              "species_id" bigint,
                              "breed_id" bigint,
                              "birth_date" date,
                              "gender" varchar,
                              "description" text,
                              "status" varchar,
                              "owner_id" bigint
);

CREATE TABLE "pet"."pet_adoption_profiles" (
                                               "pet_id" bigint PRIMARY KEY,
                                               "health_status" text,
                                               "vaccinated" boolean,
                                               "sterilized" boolean,
                                               "personality" text,
                                               "habits" text,
                                               "favorite_activities" text,
                                               "care_instructions" text,
                                               "diet" text,
                                               "adoption_requirements" text,
                                               "reason_for_adoption" text,
                                               "created_at" timestamp,
                                               "updated_at" timestamp
);

CREATE TABLE "pet"."pet_media" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "pet_id" bigint,
                                   "type" varchar,
                                   "role" varchar,
                                   "url" text,
                                   "display_order" int
);

CREATE TABLE "pet"."follow_pet" (
                                    "user_id" bigint,
                                    "pet_id" bigint,
                                    "created_at" timestamp,
                                    PRIMARY KEY ("user_id", "pet_id")
);

CREATE TABLE IF NOT EXISTS "social"."posts" (
                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "author_id" bigint,
                                  "content" text,
                                  "hashtags" text,
                                  "type" varchar,
                                  "contact_info" varchar,
                                  "location" varchar,
                                  "created_at" timestamp,
                                  "deleted_at" timestamp
);

CREATE TABLE IF NOT EXISTS "social"."post_pet" (
                                     "post_id" bigint,
                                     "pet_id" bigint,
                                     PRIMARY KEY ("post_id", "pet_id")
);

CREATE TABLE IF NOT EXISTS "social"."post_media" (
                                       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "post_id" bigint,
                                       "type" varchar,
                                       "url" text,
                                       "display_order" int
);

CREATE TABLE IF NOT EXISTS "social"."comments" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "post_id" bigint,
                                     "user_id" bigint,
                                     "parent_id" bigint,
                                     "content" text,
                                     "created_at" timestamp,
                                     "deleted_at" timestamp
);

CREATE TABLE IF NOT EXISTS "social"."likes" (
                                  "user_id" bigint,
                                  "post_id" bigint,
                                  "created_at" timestamp,
                                  PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE IF NOT EXISTS "notification"."notifications" (
                                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                "user_id" bigint,
                                                "type" varchar,
                                                "reference_id" bigint,
                                                "is_read" boolean,
                                                "created_at" timestamp
);

CREATE INDEX ON "auth"."follow_user" ("follower_id", "following_id");

COMMENT ON COLUMN "auth"."users"."id" IS 'Primary key người dùng';

COMMENT ON COLUMN "auth"."users"."email" IS 'Email đăng nhập';

COMMENT ON COLUMN "auth"."users"."username" IS 'Tên hiển thị';

COMMENT ON COLUMN "auth"."users"."password" IS 'Mật khẩu đã hash';

COMMENT ON COLUMN "auth"."users"."role" IS 'USER | ADMIN';

COMMENT ON COLUMN "auth"."users"."avatar_url" IS 'Ảnh đại diện';

COMMENT ON COLUMN "auth"."users"."bio" IS 'Mô tả hồ sơ';

COMMENT ON COLUMN "auth"."users"."is_verified" IS 'Xác minh email';

COMMENT ON COLUMN "auth"."users"."created_at" IS 'Thời điểm tạo';

COMMENT ON COLUMN "auth"."users"."deleted_at" IS 'Soft delete';

COMMENT ON TABLE "auth"."follow_user" IS 'Quan hệ theo dõi giữa người dùng';

COMMENT ON COLUMN "encyclopedia"."classes"."name" IS 'Tên hiển thị (VD: Động vật có vú)';

COMMENT ON COLUMN "encyclopedia"."classes"."code" IS 'Slug dùng cho URL';

COMMENT ON COLUMN "encyclopedia"."classes"."description" IS 'Mô tả tổng quan';

COMMENT ON TABLE "encyclopedia"."species" IS 'Species = kiến thức trung lập, cố định cho mọi loài.
Không cá nhân hóa theo hành vi nuôi.
';

COMMENT ON COLUMN "encyclopedia"."species"."name" IS 'Tên loài (VD: Chó)';

COMMENT ON COLUMN "encyclopedia"."species"."scientific_name" IS 'Tên khoa học';

COMMENT ON COLUMN "encyclopedia"."species"."description" IS 'Mô tả sinh học tổng quan';

COMMENT ON TABLE "encyclopedia"."species_attributes" IS 'Attribute đo lường cho Species.
Dùng cho section "Attribute".
';

COMMENT ON COLUMN "encyclopedia"."species_attributes"."key" IS 'size | height | weight | life_span
population | top_speed
';

COMMENT ON COLUMN "encyclopedia"."species_attributes"."value_min" IS 'Giá trị nhỏ nhất';

COMMENT ON COLUMN "encyclopedia"."species_attributes"."value_max" IS 'Giá trị lớn nhất';

COMMENT ON COLUMN "encyclopedia"."species_attributes"."unit" IS 'kg | cm | years | km/h';

COMMENT ON TABLE "encyclopedia"."species_sections" IS 'Section cố định cho Species.
Mọi loài đều phải có đủ các section này.
';

COMMENT ON COLUMN "encyclopedia"."species_sections"."code" IS 'attribute
appearance
habitat
habits_lifestyle
gallery
breed_list
recommendation
';

COMMENT ON TABLE "encyclopedia"."species_section_contents" IS 'Nội dung text cho section Species
(trừ Attribute & Gallery).
';

COMMENT ON COLUMN "encyclopedia"."species_section_contents"."language" IS 'vi | en';

COMMENT ON COLUMN "encyclopedia"."species_section_contents"."content" IS 'Nội dung markdown / html';

COMMENT ON TABLE "encyclopedia"."breeds" IS 'Breed = mức chi tiết nhất, user-centric.
Dùng cho cá nhân hóa, gợi ý, SEO.
';

COMMENT ON COLUMN "encyclopedia"."breeds"."origin" IS 'Nguồn gốc giống';

COMMENT ON COLUMN "encyclopedia"."breeds"."short_description" IS 'Mô tả ngắn hiển thị card';

COMMENT ON TABLE "encyclopedia"."breed_attributes" IS 'Attribute định tính cho giống';

COMMENT ON COLUMN "encyclopedia"."breed_attributes"."key" IS 'temperament | energy_level | shedding
trainability | friendliness
';

COMMENT ON COLUMN "encyclopedia"."breed_attributes"."value" IS 'Text hoặc enum';

COMMENT ON TABLE "encyclopedia"."breed_sections" IS 'Danh sách section có thể gán cho Breed.
Giống có thể có hoặc không từng section.
';

COMMENT ON COLUMN "encyclopedia"."breed_sections"."code" IS 'nutrition
training
health
grooming
activities
';

COMMENT ON TABLE "encyclopedia"."breed_section_mapping" IS 'Xác định breed có section nào';

COMMENT ON TABLE "encyclopedia"."breed_section_contents" IS 'Nội dung chi tiết cho section của Breed';

COMMENT ON TABLE "encyclopedia"."media" IS 'Media polymorphic cho Encyclopedia.
Gallery Species = entity_type=species
';

COMMENT ON COLUMN "encyclopedia"."media"."entity_type" IS 'class | species | breed';

COMMENT ON COLUMN "encyclopedia"."media"."entity_id" IS 'ID của entity';

COMMENT ON COLUMN "encyclopedia"."media"."type" IS 'image | video';

COMMENT ON COLUMN "encyclopedia"."media"."role" IS 'hero | gallery | thumbnail';

COMMENT ON COLUMN "pet"."pets"."birth_date" IS 'Ngày sinh (nullable nếu không rõ)';

COMMENT ON COLUMN "pet"."pets"."description" IS 'Giới thiệu pet';

COMMENT ON COLUMN "pet"."pets"."status" IS 'owned | for_adoption';

COMMENT ON TABLE "pet"."pet_adoption_profiles" IS 'Hồ sơ CHỈ tồn tại nếu pet ở trạng thái for_adoption.
Không dùng cho pet đã có chủ.
';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."pet_id" IS 'Pet tìm người nhận nuôi';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."health_status" IS 'Tình trạng sức khỏe tổng quát';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."vaccinated" IS 'Đã tiêm phòng hay chưa';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."sterilized" IS 'Đã triệt sản hay chưa';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."personality" IS 'Tính cách (hiền, nhút nhát, năng động,...)';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."habits" IS 'Thói quen sinh hoạt';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."favorite_activities" IS 'Sở thích (chạy bộ, chơi bóng,...)';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."care_instructions" IS 'Cách chăm sóc / lưu ý đặc biệt';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."diet" IS 'Chế độ ăn hiện tại';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."adoption_requirements" IS 'Yêu cầu đối với người nhận nuôi';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."reason_for_adoption" IS 'Lý do cho nhận nuôi';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."created_at" IS 'Thời điểm đăng tìm người nhận nuôi';

COMMENT ON COLUMN "pet"."pet_adoption_profiles"."updated_at" IS 'Lần cập nhật gần nhất';

COMMENT ON TABLE "pet"."pet_media" IS 'Media riêng của pet (không phải media của post)';

COMMENT ON COLUMN "pet"."pet_media"."id" IS 'Primary key media';

COMMENT ON COLUMN "pet"."pet_media"."pet_id" IS 'Thuộc pet';

COMMENT ON COLUMN "pet"."pet_media"."type" IS 'image | video';

COMMENT ON COLUMN "pet"."pet_media"."role" IS 'avatar | gallery';

COMMENT ON COLUMN "pet"."pet_media"."url" IS 'Đường dẫn media';

COMMENT ON COLUMN "pet"."pet_media"."display_order" IS 'Thứ tự hiển thị';

COMMENT ON TABLE "pet"."follow_pet" IS 'User theo dõi pet';

COMMENT ON COLUMN "pet"."follow_pet"."user_id" IS 'Người theo dõi';

COMMENT ON COLUMN "pet"."follow_pet"."pet_id" IS 'Pet được theo dõi';

COMMENT ON COLUMN "pet"."follow_pet"."created_at" IS 'Thời điểm follow';

COMMENT ON TABLE "social"."posts" IS 'Bài viết mạng xã hội.
Có thể gắn nhiều pet.
Có comment, like, media.
';

COMMENT ON COLUMN "social"."posts"."id" IS 'Primary key bài viết';

COMMENT ON COLUMN "social"."posts"."author_id" IS 'Người tạo bài viết';

COMMENT ON COLUMN "social"."posts"."content" IS 'Nội dung chính';

COMMENT ON COLUMN "social"."posts"."hashtags" IS 'Danh sách hashtag dạng text';

COMMENT ON COLUMN "social"."posts"."type" IS 'normal | adoption | sale';

COMMENT ON COLUMN "social"."posts"."contact_info" IS 'Thông tin liên hệ nếu là adoption/sale';

COMMENT ON COLUMN "social"."posts"."location" IS 'Địa điểm';

COMMENT ON COLUMN "social"."posts"."created_at" IS 'Thời điểm tạo';

COMMENT ON COLUMN "social"."posts"."deleted_at" IS 'Soft delete';

COMMENT ON TABLE "social"."post_pet" IS 'Một post có thể gắn nhiều pet.
Một pet có thể xuất hiện trong nhiều post.
';

COMMENT ON COLUMN "social"."post_pet"."post_id" IS 'Bài viết';

COMMENT ON COLUMN "social"."post_pet"."pet_id" IS 'Pet được gắn';

COMMENT ON TABLE "social"."post_media" IS 'Media của bài viết';

COMMENT ON COLUMN "social"."post_media"."type" IS 'image | video';

COMMENT ON COLUMN "social"."post_media"."url" IS 'Đường dẫn media';

COMMENT ON COLUMN "social"."post_media"."display_order" IS 'Thứ tự hiển thị';

COMMENT ON TABLE "social"."comments" IS 'Comment dạng tree (parent_id).
NULL parent_id = comment gốc.
';

COMMENT ON COLUMN "social"."comments"."id" IS 'Primary key comment';

COMMENT ON COLUMN "social"."comments"."post_id" IS 'Thuộc post';

COMMENT ON COLUMN "social"."comments"."user_id" IS 'Người comment';

COMMENT ON COLUMN "social"."comments"."parent_id" IS 'Comment cha (reply)';

COMMENT ON COLUMN "social"."comments"."content" IS 'Nội dung comment';

COMMENT ON COLUMN "social"."comments"."created_at" IS 'Thời điểm tạo';

COMMENT ON COLUMN "social"."comments"."deleted_at" IS 'Soft delete';

COMMENT ON TABLE "social"."likes" IS 'Like theo mô hình N-N.
1 user chỉ like 1 post 1 lần.
';

COMMENT ON COLUMN "social"."likes"."user_id" IS 'Người like';

COMMENT ON COLUMN "social"."likes"."post_id" IS 'Post được like';

COMMENT ON COLUMN "social"."likes"."created_at" IS 'Thời điểm like';

ALTER TABLE "auth"."follow_user" ADD FOREIGN KEY ("follower_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "auth"."follow_user" ADD FOREIGN KEY ("following_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "encyclopedia"."species" ADD FOREIGN KEY ("class_id") REFERENCES "encyclopedia"."classes" ("id");

ALTER TABLE "encyclopedia"."species_attributes" ADD FOREIGN KEY ("species_id") REFERENCES "encyclopedia"."species" ("id");

ALTER TABLE "encyclopedia"."species_section_contents" ADD FOREIGN KEY ("species_id") REFERENCES "encyclopedia"."species" ("id");

ALTER TABLE "encyclopedia"."species_section_contents" ADD FOREIGN KEY ("section_id") REFERENCES "encyclopedia"."species_sections" ("id");

ALTER TABLE "encyclopedia"."breeds" ADD FOREIGN KEY ("species_id") REFERENCES "encyclopedia"."species" ("id");

ALTER TABLE "encyclopedia"."breed_attributes" ADD FOREIGN KEY ("breed_id") REFERENCES "encyclopedia"."breeds" ("id");

ALTER TABLE "encyclopedia"."breed_section_mapping" ADD FOREIGN KEY ("breed_id") REFERENCES "encyclopedia"."breeds" ("id");

ALTER TABLE "encyclopedia"."breed_section_mapping" ADD FOREIGN KEY ("section_id") REFERENCES "encyclopedia"."breed_sections" ("id");

ALTER TABLE "encyclopedia"."breed_section_contents" ADD FOREIGN KEY ("breed_id") REFERENCES "encyclopedia"."breeds" ("id");

ALTER TABLE "encyclopedia"."breed_section_contents" ADD FOREIGN KEY ("section_id") REFERENCES "encyclopedia"."breed_sections" ("id");

ALTER TABLE "pet"."pets" ADD FOREIGN KEY ("species_id") REFERENCES "encyclopedia"."species" ("id");

ALTER TABLE "pet"."pets" ADD FOREIGN KEY ("breed_id") REFERENCES "encyclopedia"."breeds" ("id");

ALTER TABLE "pet"."pets" ADD FOREIGN KEY ("owner_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "pet"."pet_adoption_profiles" ADD FOREIGN KEY ("pet_id") REFERENCES "pet"."pets" ("id");

ALTER TABLE "pet"."pet_media" ADD FOREIGN KEY ("pet_id") REFERENCES "pet"."pets" ("id");

ALTER TABLE "pet"."follow_pet" ADD FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "pet"."follow_pet" ADD FOREIGN KEY ("pet_id") REFERENCES "pet"."pets" ("id");

ALTER TABLE "social"."posts" ADD FOREIGN KEY ("author_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "social"."post_pet" ADD FOREIGN KEY ("post_id") REFERENCES "social"."posts" ("id");

ALTER TABLE "social"."post_pet" ADD FOREIGN KEY ("pet_id") REFERENCES "pet"."pets" ("id");

ALTER TABLE "social"."post_media" ADD FOREIGN KEY ("post_id") REFERENCES "social"."posts" ("id");

ALTER TABLE "social"."comments" ADD FOREIGN KEY ("post_id") REFERENCES "social"."posts" ("id");

ALTER TABLE "social"."comments" ADD FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "social"."comments" ADD FOREIGN KEY ("parent_id") REFERENCES "social"."comments" ("id");

ALTER TABLE "social"."likes" ADD FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "social"."likes" ADD FOREIGN KEY ("post_id") REFERENCES "social"."posts" ("id");

ALTER TABLE "notification"."notifications" ADD FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");
